[[redirects]]
  from = "https://hugo.hackethical.net/*"
  to = "https://hugo.hackethical.be/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://hugo.hackethical.org/*"
  to = "https://hugo.hackethical.be/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://hackethical.net/*"
  to = "/404.html"
  status = 404
  force = true

[[redirects]]
  from = "https://hackethical.org/*"
  to = "/404.html"
  status = 404
  force = true